comment-box/config/routes.rb
CommentBox::Application.routes.draw do
  post "comments/passphrase"
  get "comments/passphrase"

  resources :comments

  root :to => 'comments#passphrase'

end

comment-box/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
end

comment-box/app/models/key.rb
class Key < ActiveRecord::Base
  attr_accessible :phrase
end

comment-box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

comment-box/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include Validators
  before_filter :check_passphrase, :except => :passphrase

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save!
        redirect_to comment_url(@comment)
      else
        render :action => "new"
      end
    end
  end

  def passphrase
    if params[:passphrase]
      @phrase = params[:passphrase]
      if Validators::Validator.check_phrase(@phrase)
        session[:passphrase] = @phrase
        redirect_to :controller => 'comments', :action => 'index'
      else
        flash[:notice] = "Passphrase not found. Try again."
      end
    end
  end

  def check_passphrase
    unless session[:passphrase]
      flash[:error] = "Please enter your passphrase"
      redirect_to root_url
    end
  end
end

comment-box/app/helpers/application_helper.rb
module ApplicationHelper
end

comment-box/app/helpers/comments_helper.rb
module CommentsHelper
end

comment-box/app/views/comments/index.html.erb
<h1>Welcome to Comment Box</h1>

<%= link_to "Drop in a new comment", new_comment_path %>
<br>
<br>
<% @comments.each do |c| %>
<div class="comment">
<%= c.body %>
</div>
<% end %>

comment-box/app/views/comments/new.html.erb
<%= form_for @comment do |c| %>
<%= c.label "What do you want to see?" %>
<%= c.text_field "body" %>
<%= c.submit %>

<% end %>

comment-box/app/views/comments/passphrase.html.erb
Enter your passphrase
<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>
<%= form_tag :controller => "comments", :action => "passphrase" %>
<%= text_field_tag "passphrase" %>
<%= submit_tag "Go!" ,:method => :post %>

comment-box/app/views/comments/show.html.erb
<%= link_to "View all comments", comments_path %>
<%= @comment.body %>

comment-box/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommentBox</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="box">
<%= yield %>
</div>
</body>
</html>